In [5]:
from transformers import BertConfig, BertModel
## Hugging Face Examples:
config = BertConfig()
model = BertModel(config)

In [1]:
from BERT.config_bert import BertConfig
from BERT.modeling_bert import BertModel

In [2]:
config = BertConfig(abc = 123)
model = BertModel(config)

In [3]:
import torch
input = torch.ones(1, 1)

In [4]:
model(input)

tensor([[ 0.0048, -0.0419, -0.0041,  0.0035,  0.0312,  0.0051,  0.0094, -0.0374,
          0.0263,  0.0140]], grad_fn=<AddmmBackward0>)

In [5]:
model_2 = BertModel(BertConfig())

In [6]:
model_2(input)

tensor([[-0.0160, -0.0173, -0.0060,  0.0016, -0.0071, -0.0245, -0.0030,  0.0128,
          0.0181,  0.0102]], grad_fn=<AddmmBackward0>)

In [7]:
model.save_pretrained("test")

In [8]:
model_3 = BertModel.from_pretranied("test")

In [9]:
model(input)

tensor([[ 0.0048, -0.0419, -0.0041,  0.0035,  0.0312,  0.0051,  0.0094, -0.0374,
          0.0263,  0.0140]], grad_fn=<AddmmBackward0>)

In [10]:
model_2(input)

tensor([[-0.0160, -0.0173, -0.0060,  0.0016, -0.0071, -0.0245, -0.0030,  0.0128,
          0.0181,  0.0102]], grad_fn=<AddmmBackward0>)

In [11]:
model_3(input)

tensor([[ 0.0048, -0.0419, -0.0041,  0.0035,  0.0312,  0.0051,  0.0094, -0.0374,
          0.0263,  0.0140]], grad_fn=<AddmmBackward0>)

In [12]:
model.config.abc

123

In [13]:
model_2.config.abc

AttributeError: 'BertConfig' object has no attribute 'abc'

In [14]:
model_3.config.abc

123